-- Run this once in Supabase -> SQL Editor.
-- Adds Elias's persistent els currency without touching existing tables.

create table if not exists public.economy_users (
  id bigint generated by default as identity primary key,
  guild_id text not null,
  discord_id text not null,
  balance integer not null default 0 check (balance >= 0),
  last_daily_at timestamptz,
  updated_at timestamptz not null default now(),
  unique (guild_id, discord_id)
);

create index if not exists economy_users_lookup_idx
  on public.economy_users(guild_id, discord_id);
