-- Elias database schema
-- Run this once in Supabase -> SQL Editor.

create table if not exists public.channels (
  channel_id text primary key,
  guild_id text not null,
  mode text not null check (mode in ('main', 'semi', 'blocked')),
  updated_at timestamptz not null default now()
);

create index if not exists channels_guild_id_idx on public.channels(guild_id);

create table if not exists public.users (
  discord_id text primary key,
  username text not null,
  display_name text,
  updated_at timestamptz not null default now()
);

create table if not exists public.memories (
  id bigint generated by default as identity primary key,
  guild_id text not null,
  discord_id text not null,
  memory text not null,
  importance real not null default 0.5 check (importance >= 0 and importance <= 1),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists memories_user_idx on public.memories(guild_id, discord_id, updated_at desc);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  guild_id text not null,
  channel_id text not null,
  discord_id text not null,
  username text not null,
  content text not null,
  created_at timestamptz not null default now()
);

create index if not exists messages_channel_idx on public.messages(guild_id, channel_id, created_at desc);

-- This bot runs entirely server-side. It uses a Supabase secret key, so RLS is not
-- required for the bot connection. Do NOT expose the secret key to a browser/client.
