-- Elias database schema
-- Run this once in Supabase -> SQL Editor.

create table if not exists public.stocks (
  id bigint generated by default as identity primary key,
  symbol text not null unique,
  name text not null,
  price numeric(12,2) not null default 75.00 check (price >= 0),
  total_supply integer not null default 150 check (total_supply > 0),
  created_at timestamptz not null default now()
);

alter table public.stocks add column if not exists total_supply integer not null default 150;
update public.stocks set total_supply = 150 where total_supply is null or total_supply <> 150;

create table if not exists public.stock_holdings (
  discord_id text not null,
  stock_id bigint not null references public.stocks(id) on delete cascade,
  quantity integer not null check (quantity > 0),
  primary key (discord_id, stock_id)
);

create index if not exists stock_holdings_user_idx on public.stock_holdings(discord_id);

insert into public.stocks (symbol, name, price)
values
  ('ELIAS', 'Elias', 75.00),
  ('NOVA', 'Nova', 75.00),
  ('BYTE', 'Byte', 75.00)
on conflict (symbol) do nothing;

create table if not exists public.teal_economy (
  guild_id text not null,
  discord_id text not null,
  balance bigint not null default 0 check (balance >= 0),
  total_wagered bigint not null default 0 check (total_wagered >= 0),
  stats jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (guild_id, discord_id)
);

create index if not exists teal_economy_guild_balance_idx on public.teal_economy(guild_id, balance desc);
create index if not exists teal_economy_guild_wagered_idx on public.teal_economy(guild_id, total_wagered desc);