-- Elias database schema
-- Run this once in Supabase -> SQL Editor.

create table if not exists public.stocks (
  id bigint generated by default as identity primary key,
  symbol text not null unique,
  name text not null,
  price numeric(12,2) not null default 75.00 check (price >= 0),
  total_supply integer not null default 150 check (total_supply > 0),
  created_at timestamptz not null default now()
);

alter table public.stocks add column if not exists total_supply integer not null default 150;
update public.stocks set total_supply = 150 where total_supply is null or total_supply <> 150;

create table if not exists public.stock_holdings (
  discord_id text not null,
  stock_id bigint not null references public.stocks(id) on delete cascade,
  quantity integer not null check (quantity > 0),
  reserved_quantity integer not null default 0 check (reserved_quantity >= 0 and reserved_quantity <= quantity),
  locked_until timestamptz,
  primary key (discord_id, stock_id)
);

alter table public.stock_holdings add column if not exists reserved_quantity integer not null default 0;
alter table public.stock_holdings add column if not exists locked_until timestamptz;
update public.stock_holdings set reserved_quantity = 0 where reserved_quantity is null;
create index if not exists stock_holdings_user_idx on public.stock_holdings(discord_id);
create index if not exists stock_holdings_locked_until_idx on public.stock_holdings(locked_until);

insert into public.stocks (symbol, name, price)
values
  ('ELIAS', 'Elias', 75.00),
  ('NOVA', 'Nova', 75.00),
  ('BYTE', 'Byte', 75.00)
on conflict (symbol) do nothing;

create table if not exists public.teal_economy (
  guild_id text not null,
  discord_id text not null,
  balance bigint not null default 0 check (balance >= 0),
  total_wagered bigint not null default 0 check (total_wagered >= 0),
  stats jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (guild_id, discord_id)
);

create index if not exists teal_economy_guild_balance_idx on public.teal_economy(guild_id, balance desc);
alter table public.teal_economy add column if not exists total_deposited bigint not null default 0 check (total_deposited >= 0);
alter table public.teal_economy add column if not exists total_daily_claimed bigint not null default 0 check (total_daily_claimed >= 0);
alter table public.teal_economy add column if not exists last_daily bigint not null default 0 check (last_daily >= 0);

create index if not exists teal_economy_guild_wagered_idx on public.teal_economy(guild_id, total_wagered desc);